### ISSUE TITLE
Update SharpZipLib once #76 gets released in a new version

### ISSUE THREAD

**Issue by bbenoist** [fsharp/FAKE#775]
When using [`FAKE.ZipHelper.Unzip`](https://github.com/fsharp/FAKE/blob/653d5013cceb80a9f0be1d36bc471f52a8d53d6b/src/app/FakeLib/ZipHelper.fs#L88) to extract the latest [CMake](http://cmake.org) release, I encountered an issue with SharpZipLib:

```
Error:
ICSharpCode.SharpZipLib.Zip.ZipException: Compressed size mismatch between central header(4401293) and local header(0)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.TestLocalHeader(ZipEntry entry, HeaderTest tests)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int64 entryIndex)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)
   at Fake.ZipHelper.Unzip(String target, String fileName) in FakeLib\ZipHelper.fs:line 98
   at FSI_0001.Build.clo@52-5.Invoke(Unit _arg4) in build.fsx:line 53
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in FakeLib\TargetHelper.fs:line 411
```

The zip file in question can be downloaded from [`http://www.cmake.org/files/v3.2/cmake-3.2.2-win32-x86.zip`](http://www.cmake.org/files/v3.2/cmake-3.2.2-win32-x86.zip).

Considering an [already submitted issue](https://github.com/icsharpcode/SharpZipLib/issues/41), it appears to be directly related with [SharpZipLib](https://github.com/icsharpcode/SharpZipLib).

I have opened a [PR including the suggested fix](https://github.com/icsharpcode/SharpZipLib/pull/76).
Once/if it gets included in a new SharpZipLib release, I would appreciate an update of the library in FAKE. :wink:

**Comment by bbenoist** [comment]
@forki Are you OK if I make a PR ditching SharpZipLib for another implementation?

**Comment by forki** [comment]
SharpZipLib is bundled with FAKE for a very long time. I assume it will
break a lot of stuff if we remove it completely.

**Comment by McNeight** [comment]
Don't give up on SharpZipLib just yet. I'm working my way through the backlog, and hope to have a new and improved release "soon".

-Neil

**Comment by matthid** [comment]
I guess this has been fixed since the PR on SharpZipLib is merged?

**Comment by codebrain** [comment]
Can confirm this is still a problem with zip files created using CMAKE.

**Comment by matthid** [comment]
@codebrain can you open a new issue with steps on how to reproduce, a lot changed since this was reported...
